#!/bin/bash

set -e

cargo build -r
cargo build -r --target x86_64-pc-windows-gnu

VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump target/release/vsbm > /tmp/vsbm.log && mv /tmp/vsbm.log native-vulkan.log
VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_api_dump WGPU_BACKEND=dx12 \
    wine target/x86_64-pc-windows-gnu/release/vsbm.exe > /tmp/vsbm.log && mv /tmp/vsbm.log wine-vkd3d.log

./extract-frame9

